In [2]:
import array
ptr=array.array('i',[67,58,49])
for i in range(0,3):
    print(ptr[i],end="  ")

67  58  49  

In [3]:
import numpy as num
a1=num.array([5,6,7,8])
print("a1 = ",a1)

a1 =  [5 6 7 8]


# append and insert

In [4]:
import numpy as num
a1=num.array([5,6,7,8])
print("a1 = ",a1)
a1=num.append(a1,67)
print("a1 = ",a1)

a1 =  [5 6 7 8]
a1 =  [ 5  6  7  8 67]


In [5]:
import numpy as num
a1=num.array([5,6,7,8])
print("a1 = ",a1)
a1=num.append(a1,67)
print("a1 = ",a1)
a1=num.insert(a1,3,100)
print("a1 = ",a1)

a1 =  [5 6 7 8]
a1 =  [ 5  6  7  8 67]
a1 =  [  5   6   7 100   8  67]


In [6]:
help(num.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [26]:
a1=num.array([[2,2,2],[3,3,3],[6,6,6]])
print("a1 = ",a1)
a1=num.insert(a1,2,5,axis=0)    #axis=0 (column) and axis=1 (row)   axis=-1(row)   axis=-2(column) 
print("a1 = ",a1)

a1 =  [[2 2 2]
 [3 3 3]
 [6 6 6]]
a1 =  [[2 2 2]
 [3 3 3]
 [5 5 5]
 [6 6 6]]


# copy and sort

In [27]:
b1=num.array([[4,35],[9,8]])
print("Before sort b1 = ",b1)
b1=num.sort(b1,axis=0)
print("After sort b1 = ",b1)

Before sort b1 =  [[ 4 35]
 [ 9  8]]
After sort b1 =  [[ 4  8]
 [ 9 35]]


In [28]:
import numpy as num
a2 = num.array([[2,6,9],[8,1,7],[6,5,4]])
print("a2 = ",a2)
a3 = num.copy(a2)
print("a3 =",a3)
a3 = num.sort(a3 ,axis = 0)
print("Sorted Array a3 = ",a3)

a2 =  [[2 6 9]
 [8 1 7]
 [6 5 4]]
a3 = [[2 6 9]
 [8 1 7]
 [6 5 4]]
Sorted Array a3 =  [[2 1 4]
 [6 5 7]
 [8 6 9]]


# arange function

In [30]:
d=num.arange(20)
print("d = ",d)

d =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
t=num.arange(1,10,2)
print(t)

[1 3 5 7 9]


# reashape function

In [35]:
r=num.arange(8)
r=num.arange(8).reshape(2,3)
print(r)

ValueError: cannot reshape array of size 8 into shape (2,3)