# find out the solution of linera equ

In [7]:
import numpy as num
m1=num.matrix("3,1,2;3,2,5;6,7,8")
m2=num.matrix("2,-1,3").transpose()
print("m1=\n",m1)
print("m2=\n",m2)
ans=num.linalg.solve(m1,m2)
print("ans is:\n",ans)

m1=
 [[3 1 2]
 [3 2 5]
 [6 7 8]]
m2=
 [[ 2]
 [-1]
 [ 3]]
ans is:
 [[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]


In [6]:
import numpy as num
m1=num.matrix("3,1,2;3,2,5;6,7,8")
m2=num.matrix("2,-1,3").transpose()
print("m1=\n",m1)
print("m2=\n",m2)
ans=num.linalg.solve(m1,m2)
print("ans is:\n",ans)

m1=
 [[3 1 2]
 [3 2 5]
 [6 7 8]]
m2=
 [[ 2]
 [-1]
 [ 3]]
ans is:
 [[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]
