In [2]:
import numpy as num
m1=num.matrix('3,6;7,2;1,9')
print("m1=\n",m1)


m1=
 [[3 6]
 [7 2]
 [1 9]]


In [3]:
import numpy as num
m1=num.matrix('3,6;7,2;1,9')
print("m1=\n",m1)
sum_ele=num.sum(m1)
print("sum_ele=",sum_ele)

m1=
 [[3 6]
 [7 2]
 [1 9]]
sum_ele= 28


In [4]:
import numpy as num
m1=num.matrix('3,6;7,2;1,9')
print("m1=\n",m1)
sum_ele_clm=num.sum(m1,axis=0)
print("sum_ele_clm=",sum_ele_clm)

m1=
 [[3 6]
 [7 2]
 [1 9]]
sum_ele_clm= [[11 17]]


In [5]:
import numpy as num
m1=num.matrix('3,6;7,2;1,9')
print("m1=\n",m1)
sum_ele_clm=num.sum(m1,axis=1)
print("sum_ele_clm=",sum_ele_clm)

m1=
 [[3 6]
 [7 2]
 [1 9]]
sum_ele_clm= [[ 9]
 [ 9]
 [10]]


In [6]:
import numpy as num
m1=num.matrix('5,3,6;1,8,4;2,5,9')
print("m1=\n",m1)
m2=num.matrix('1,2,3;4,5,6;7,8,9')
print("m2=\n",m2)
m3=m1+m2;
print("m3=n",m3)

m1=
 [[5 3 6]
 [1 8 4]
 [2 5 9]]
m2=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
m3=n [[ 6  5  9]
 [ 5 13 10]
 [ 9 13 18]]


In [7]:
import numpy as num
m1=num.matrix('5,3,6;1,8,4;2,5,9')
print("m1=\n",m1)
m2=num.matrix('1,2,3;4,5,6;7,8,9')
print("m2=\n",m2)
m3=m1*m2;
print("m3=n",m3)

m1=
 [[5 3 6]
 [1 8 4]
 [2 5 9]]
m2=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
m3=n [[ 59  73  87]
 [ 61  74  87]
 [ 85 101 117]]


# tranpose

In [8]:
import numpy as np
m1=np.matrix('3,4,4;2,5,6;1,7,8')
print("m1 =\n",m1)
m2=np.transpose(m1)
print("m2 =\n",m2)

m1 =
 [[3 4 4]
 [2 5 6]
 [1 7 8]]
m2 =
 [[3 2 1]
 [4 5 7]
 [4 6 8]]


In [9]:
import numpy as np
m1=np.matrix('3,4,4;2,5,6;1,7,8')
print("m1 =\n",m1)
m2=m1.T
print("m2 =\n",m2)

m1 =
 [[3 4 4]
 [2 5 6]
 [1 7 8]]
m2 =
 [[3 2 1]
 [4 5 7]
 [4 6 8]]


# determinant 

In [10]:
import numpy as np
m1=np.matrix('3,4,4;2,5,6;1,7,8')
print("m1 =\n",m1)
m=np.linalg.det(m1)
print("determinant is =",m)

m1 =
 [[3 4 4]
 [2 5 6]
 [1 7 8]]
determinant is = -10.000000000000002


# identity matrix

In [1]:
import numpy as np
m1=np.identity(3)
print("m1 =\n",m1)
m=np.linalg.det(m1)
print("determinant is =",m)

m1 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
determinant is = 1.0


In [10]:
import numpy as np
m1=np.matrix('5,3,6;1,8,4;2,5,9')
print("m1 =\n",m1)
inverse = np.linalg.inv(m1)
inverse
# print(inverse)

m1 =
 [[5 3 6]
 [1 8 4]
 [2 5 9]]


matrix([[ 0.27225131,  0.01570681, -0.18848168],
        [-0.0052356 ,  0.17277487, -0.07329843],
        [-0.05759162, -0.09947644,  0.19371728]])

In [11]:
import numpy as np
m1=np.matrix('3,4,4;2,5,6;1,7,8')
print("m1 =\n",m1)
m=np.linalg.eig(m1)
print("m is =\n",m)
print("eigen values: \n",m[0])
print("eigen vector: \n",m[1])

m1 =
 [[3 4 4]
 [2 5 6]
 [1 7 8]]
m is =
 (array([14.18831112,  2.14089896, -0.32921008]), matrix([[-0.44882124, -0.8958623 ,  0.17124127],
        [-0.55503011, -0.20289422, -0.76427014],
        [-0.70035781,  0.39530328,  0.6217456 ]]))
eigen values: 
 [14.18831112  2.14089896 -0.32921008]
eigen vector: 
 [[-0.44882124 -0.8958623   0.17124127]
 [-0.55503011 -0.20289422 -0.76427014]
 [-0.70035781  0.39530328  0.6217456 ]]


In [12]:
import numpy as np
m1=np.matrix('5,3,6;1,8,4;2,5,9')
print("m1 =\n",m1)
m2 = np.linalg.eig(m1)
#at index 0 eigen values are stored and at index 1 eigen vectors are stored
print('eigen_values = ',m2[0])
print('eigen_vectors = ',m2[1])

m1 =
 [[5 3 6]
 [1 8 4]
 [2 5 9]]
eigen_values =  [14.49017801  2.79678051  4.71304148]
eigen_vectors =  [[-0.57094364 -0.90708542  0.82596536]
 [-0.49270834 -0.13275813 -0.51901711]
 [-0.6567053   0.39946378  0.22000559]]
